### PR TITLE
Feature/code section

### PR DESCRIPTION
**Pull request by RobsonOlv**
#### What is the purpose of this pull request?

To update the curl style and create the structure of the try it section.

#### What problem is this solving?

The style of the curl section doesn't match the expected design in Figma. In addition, the test page needs the try it section that contains the store URL variables and the auth section (with auth keys), after all, Rapidoc-mini use requires the URL params and keys input to generate the correct curl request.

[You can find more information here :book:](https://www.notion.so/vtexhandbook/Estilizar-code-curl-section-da-API-reference-31418fc60aef43fea492baa3ba9fc8af)

**In the future, we'll need to move the Try section to the right side of the page, as the prototype in Figma.**

#### How should this be manually tested?

Go to [this page](https://deploy-preview-73--elated-hoover-5c29bf.netlify.app/) and check:
- The try it section style compared with the [Figma](https://www.figma.com/file/Lx6sXdrw9KEvtSEKWttmv8/Developer-Portal?node-id=6309%3A379335) (ignoring the request indentation in Figma)
- The Base URL works, and autocomplete the final URL below.
- You can copy the generated URL
- After filling in the header auth and the URL variables, click on the TEST METHOD button and check if the generated curl request is correct.
- For any point, compare with the actual behavior on the respective page in [Developer portal](https://developers.vtex.com/vtex-rest-api/reference/get-to-know-vtex-apis)

| This PR | Developer portal |
| ----------- | ----------- |
| [Get Product and SKU IDs](https://deploy-preview-73--elated-hoover-5c29bf.netlify.app/docs/api-reference/catalog) | [DP Page](https://developers.vtex.com/vtex-rest-api/reference/catalog-api-get-products-skus) |
| [Cart simulation](https://deploy-preview-73--elated-hoover-5c29bf.netlify.app/docs/api-reference/checkout) | [DP page](https://developers.vtex.com/vtex-rest-api/reference/cartsimulation) |
| [Retrieve Token](https://deploy-preview-73--elated-hoover-5c29bf.netlify.app/docs/api-reference/antifraud) | [DP Page](https://developers.vtex.com/vtex-rest-api/reference/1retrievetoken) |
| [Get GiftCard Provider by ID](https://deploy-preview-73--elated-hoover-5c29bf.netlify.app/docs/api-reference/giftcard) | [DP Page](https://developers.vtex.com/vtex-rest-api/reference/getgiftcardproviderbyid) |

#### Screenshots or example usage

| Before | After |
| ----------- | ----------- |
|image|image|

Comparing the actual try section with the expected on Figma:
| This PR | Figma |
| ----------- | ----------- |
|image|image|

https://user-images.githubusercontent.com/42784961/187749913-05ee2ba4-3826-4773-a246-9f9b2d9194b9.mp4

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Comment by brunoamui** [comment]
Havendo espaço horizontal, o componente de baseUrl e de auth deveriam ficar lado a lado. Dá pra conseguir isso facilmente com [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

**Comment by RobsonOlv** [comment]
> Havendo espaço horizontal, o componente de baseUrl e de auth deveriam ficar lado a lado. Dá pra conseguir isso facilmente com [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

Esse espaço horizontal é temporário. Seguindo o protótipo do Figma, toda a seção `Try it` ficará no canto direito da página seguindo essa ordem:

image

Em telas menores a estrutura é um pouco diferente, mas ambos os comportamentos preferi por deixar pra tasks futuras dada a complexidade de fazê-las e o tamanho desse PR.

**Review by amandascm — APPROVED** [review]
Amazing contribution! thanks for the very explanatory documentation 🚀

**Review by leonardoAnjos16 — APPROVED** [review]
LGTM 💯

**Review by brunoamui — APPROVED** [review]
LGTM

**Pull request merged**
