### PR TITLE
Feature/response section

### PR DESCRIPTION
**Pull request by amandascm**
#### What is the purpose of this pull request?

To update the API references response section according to the expected design.

#### What problem is this solving?

The absence of a response section - which displays possible responses to methods and paths with their respective codes and other attributes - that follows the visual design provided for it in figma.

_*NOTE: this contribution only included the restructuring of the response section and the adaptation between available information and the available design project. Future tasks will be destined to improve the modal design._

[Further information about this contribution - such as detailed description, related problems and solutions - can be found here.
](https://www.notion.so/vtexhandbook/Estilizar-Response-section-da-API-reference-df7f70dff349461d9926e68590660902)

#### How should this be manually tested?

[Please access this preview link](https://deploy-preview-65--elated-hoover-5c29bf.netlify.app/) and **check if the response section styling of any API reference respects the provided design and if its modal is working properly**.

#### Screenshots or example usage

https://user-images.githubusercontent.com/39717968/183747231-b1efef77-68e2-4268-9610-4bcb701b53a2.mp4

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

### CODE REVIEW

**Review by leonardoAnjos16 — APPROVED** [review]
Very nice!! I just have a couple of suggestions. Not necessarily for this PR, because they might be hard to implement, but I think it would make the user experience better if the header automatically hid (and stayed hidden) when the modal appears. Also, it would be nice if the user weren't able to scroll the page when the modal is active.

I also think we could make the modal's scrollbar look something like the one we currently use at the dropdown menu of the Developer's Portal.

What do you think?

**Comment by amandascm** [comment]
> Very nice!! I just have a couple of suggestions. Not necessarily for this PR, because they might be hard to implement, but I think it would make the user experience better if the header automatically hid (and stayed hidden) when the modal appears. Also, it would be nice if the user weren't able to scroll the page when the modal is active.
> 
> I also think we could make the modal's scrollbar look something like the one we currently use at the dropdown menu of the Developer's Portal.
> 
> What do you think?

I totally agree! we can work better on the visual and usability of the modal, I will add this observation to the PR description and create a new task focused on these aspects.
One more suggestion that might be a nice change is to make the modal header fixed and only the rest of its content scrollable (when needed) so that the response code is always visible whenever the user looks for something inside the modal.

**Review by RobsonOlv — APPROVED** [review]
LGTM :rocket:

**Review by melissafalcao — APPROVED** [review]
LGTM 🎇

**Pull request merged**
